version: '3.4'

services:
  server_develop:
    privileged: true
    build:
      context: ../
      dockerfile: ./neuromodulation/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /var/sinz-shared:/data
      - /home/eoffenberg/Projects:/project
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    runtime: nvidia
    shm_size: 40g